// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/sdivyansh59/huma-project-starter/app/greeting"
	"github.com/sdivyansh59/huma-project-starter/app/setup"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the app instance
func InitializeApp() (*App, error) {
	mux := setup.ProvideSingletonChiRouter()
	api := setup.ProvideSingletonHuma(mux)
	defaultConfig := setup.GetDefaultConfig()
	controller := greeting.NewController()
	controllers := setup.InitializeControllers(controller)
	app := newApp(mux, api, defaultConfig, controllers)
	return app, nil
}
